export const REQUEST_FETCH_USERS = 'REQUEST_FETCH_USERS';
export const FETCH_USERS = 'FETCH_USERS';

export const SET_USERS_SORT = 'SET_USERS_SORT';
export const SET_USERS_FILTERS = 'SET_USERS_FILTERS';

export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
