export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS';
export const USERS_FETCH_FAILURE = 'USERS_FETCH_FAILURE';
export const SET_USERS_SORT = 'SET_USERS_SORT';

export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
